-- Comercio Digital - Busqueda tolerante a errores y sinonimos.
-- Mejora el motor existente sin cambiar su contrato con el frontend.

create extension if not exists unaccent with schema extensions;
create extension if not exists pg_trgm with schema extensions;

create table if not exists public.search_synonyms (
  id bigint generated by default as identity primary key,
  canonical_term text not null,
  synonym text not null,
  created_at timestamptz not null default now(),
  unique (canonical_term, synonym)
);

alter table public.search_synonyms enable row level security;

drop policy if exists "Public can read search synonyms" on public.search_synonyms;
create policy "Public can read search synonyms"
on public.search_synonyms
for select
to anon, authenticated
using (true);

drop policy if exists "Admins can manage search synonyms" on public.search_synonyms;
create policy "Admins can manage search synonyms"
on public.search_synonyms
for all
to authenticated
using (
  exists (
    select 1 from public.profiles
    where profiles.id = (select auth.uid())
      and profiles.role in ('admin', 'super_admin')
  )
)
with check (
  exists (
    select 1 from public.profiles
    where profiles.id = (select auth.uid())
      and profiles.role in ('admin', 'super_admin')
  )
);

grant select on public.search_synonyms to anon, authenticated;
grant insert, update, delete on public.search_synonyms to authenticated;

insert into public.search_synonyms (canonical_term, synonym) values
  ('telefono', 'celular'),
  ('telefono', 'smartphone'),
  ('telefono', 'movil'),
  ('calzado', 'zapatos'),
  ('calzado', 'tenis'),
  ('calzado', 'zapatillas'),
  ('perfume', 'fragancia'),
  ('perfume', 'locion'),
  ('perfume', 'colonia'),
  ('ropa', 'prendas'),
  ('ropa', 'vestuario'),
  ('computador', 'computadora'),
  ('computador', 'pc'),
  ('portatil', 'laptop'),
  ('audifonos', 'auriculares'),
  ('memoria', 'ram'),
  ('almacenamiento', 'capacidad')
on conflict (canonical_term, synonym) do nothing;

create or replace function public.search_marketplace_products(
  search_query text default '',
  city_query text default '',
  category_slug text default '',
  subcategory_filter uuid default null,
  minimum_price numeric default null,
  maximum_price numeric default null,
  result_limit integer default 100
)
returns table (
  product_id uuid,
  relevance integer
)
language sql
stable
security invoker
set search_path = public, extensions
as $$
  with base_products as (
    select
      p.id,
      p.updated_at,
      lower(extensions.unaccent(trim(coalesce(search_query, '')))) as normalized_query,
      lower(extensions.unaccent(concat_ws(
        ' ',
        p.name,
        p.description,
        b.name,
        b.city,
        c.name,
        sc.name,
        coalesce((
          select string_agg(pav.value, ' ')
          from public.product_attribute_values pav
          where pav.product_id = p.id
        ), ''),
        coalesce((
          select string_agg(concat_ws(' ', pv.name, pv.option_values::text), ' ')
          from public.product_variants pv
          where pv.product_id = p.id
            and pv.is_active = true
            and pv.stock > 0
        ), '')
      ))) as base_document,
      lower(extensions.unaccent(p.name)) as normalized_name,
      lower(extensions.unaccent(coalesce(c.name, ''))) as normalized_category,
      lower(extensions.unaccent(coalesce(sc.name, ''))) as normalized_subcategory,
      lower(extensions.unaccent(b.name)) as normalized_business
    from public.products p
    join public.businesses b on b.id = p.business_id
    left join public.categories c on c.id = p.category_id
    left join public.subcategories sc on sc.id = p.subcategory_id
    where p.status = 'active'
      and p.moderation_status = 'approved'
      and b.status = 'active'
      and (p.stock is null or p.stock > 0)
      and (
        trim(coalesce(city_query, '')) = ''
        or lower(extensions.unaccent(b.city)) like
          '%' || lower(extensions.unaccent(trim(city_query))) || '%'
      )
      and (trim(coalesce(category_slug, '')) = '' or c.slug = category_slug)
      and (subcategory_filter is null or sc.id = subcategory_filter)
      and (minimum_price is null or p.price >= minimum_price)
      and (maximum_price is null or p.price <= maximum_price)
  ),
  searchable_products as (
    select
      base_products.*,
      trim(concat_ws(
        ' ',
        base_document,
        coalesce((
          select string_agg(
            lower(extensions.unaccent(s.canonical_term || ' ' || s.synonym)),
            ' '
          )
          from public.search_synonyms s
          where exists (
            select 1
            from public.search_synonyms matched_synonym
            where matched_synonym.canonical_term = s.canonical_term
              and (
                base_document like '%' || lower(extensions.unaccent(matched_synonym.canonical_term)) || '%'
                or base_document like '%' || lower(extensions.unaccent(matched_synonym.synonym)) || '%'
              )
          )
        ), '')
      )) as search_document
    from base_products
  ),
  token_matches as (
    select
      searchable_products.*,
      coalesce((
        select count(*)::integer
        from unnest(regexp_split_to_array(normalized_query, '\s+')) as token
        where length(token) > 1
      ), 0) as token_count,
      coalesce((
        select count(*)::integer
        from unnest(regexp_split_to_array(normalized_query, '\s+')) as token
        where length(token) > 1
          and search_document like '%' || token || '%'
      ), 0) as matched_tokens
    from searchable_products
  ),
  scored_products as (
    select
      id,
      updated_at,
      normalized_query,
      token_count,
      matched_tokens,
      (
        case when normalized_name = normalized_query then 140 else 0 end +
        case when normalized_name like '%' || normalized_query || '%' and normalized_query <> '' then 65 else 0 end +
        case when normalized_category like '%' || normalized_query || '%' and normalized_query <> '' then 35 else 0 end +
        case when normalized_subcategory like '%' || normalized_query || '%' and normalized_query <> '' then 35 else 0 end +
        case when normalized_business like '%' || normalized_query || '%' and normalized_query <> '' then 25 else 0 end +
        case when search_document like '%' || normalized_query || '%' and normalized_query <> '' then 25 else 0 end +
        case
          when token_count > 0 then round((matched_tokens::numeric / token_count::numeric) * 45)::integer
          else 0
        end +
        round(greatest(
          similarity(normalized_name, normalized_query),
          word_similarity(normalized_query, search_document)
        ) * 55)::integer
      ) as score,
      greatest(
        similarity(normalized_name, normalized_query),
        word_similarity(normalized_query, search_document)
      ) as fuzzy_match
    from token_matches
  )
  select id, case when normalized_query = '' then 1 else score end
  from scored_products
  where normalized_query = ''
     or score >= 20
     or fuzzy_match >= 0.28
     or (token_count > 0 and matched_tokens = token_count)
  order by
    case when normalized_query = '' then 1 else score end desc,
    updated_at desc
  limit least(greatest(coalesce(result_limit, 100), 1), 200);
$$;

grant execute on function public.search_marketplace_products(
  text,
  text,
  text,
  uuid,
  numeric,
  numeric,
  integer
) to anon, authenticated;
